### ISSUE TITLE
Integration with CRA?

### ISSUE THREAD

**Issue by reflog** [service-mocker/service-mocker#16]
Hi guys,
This project is amazing!
Would you be so kind as to demonstrate how to integrate it with create-react-app application?
I've tried ejecting, adding additional entry point (so it would split server.js from bundle), but it only works in legacy mode.

Any tips would be highly appreciated!

Thanks in advance

**Comment by idiotWu** [comment]
Is there a link to the repository (a minimal example of your code) so that we can debug it ourselves?

**Comment by reflog** [comment]
Sure thing, here it is: https://github.com/reflog/mock-test
A basic app, right after 'eject', I left a hint here: https://github.com/reflog/mock-test/blob/master/src/index.js#L6

Thanks in advance!

**Comment by idiotWu** [comment]
Ah, I think the problem is that you're serving server script from `'/static/js/src/server.js'`. As per [spec](https://w3c.github.io/ServiceWorker/#selection):

> the service worker client attempts to consult a service worker registration whose scope url matches its creation URL.

According to the [Match Service Worker Registration](https://w3c.github.io/ServiceWorker/#match-service-worker-registration) algorithm below, we can infer that **the max scope for a service worker is the location of the worker script itself.**

So in your case, you can not claim the worker unless current page's location is nested under `/static/js/src`:

| location | matches(modern mode) |
| -------- | :-------: |
| `http://localhost:3000/`         | ❌  |  
| `http://localhost:3000/static/js/src/index.html`         |✅ |  
| `http://localhost:3000/static/js/src/what/ever/`         |✅ |

Sadly, up to now, we could only suggest you serve the `server.js` script from the root path of your app, i.e. `http://localhost:3000/server.js`. Since modifying `output.filename` option in webpack's config may affect the whole app, it's recommended to add a `proxy` option for `webpack-dev-server`:

```js
{
  ...
  // at scripts/start.js#L261
  proxy: {
    '/server.js': {
      pathRewrite: {
        '^/': '/static/js/src/'
      },
      target: {
        host: host,
        protocol: protocol,
        port: port
      }
    }
  }
}
```

Then in `src/index.js`:

```js
const client = createClient('server.js');
```

@VincentBel maybe we need to show a warning when the path of server script is non-root?

**Comment by idiotWu** [comment]
@reflog thanks to the detailed example, I found another potential issue: all chunks are inserted into `index.html` via `html-webpack-plugin`. I think it may be better to exclude your server script here:

```diff
plugins: [
  ...
  // at config/webpack.config.dev.js#L197
  new HtmlWebpackPlugin({
    inject: true,
    template: paths.appHtml,
+   chunks: ['src/app']
  }),
]
```

**Comment by reflog** [comment]
This is awesome, thank you! Will give it a shot and report back

**Comment by reflog** [comment]
Yep. Works **perfectly**. Thank you!

**Comment by idiotWu** [comment]
@reflog hey dude, we found another easier solution 😆 . If you are using the `1.0.3` version, you can simply add the following options to `webpack-dev-server`:

```js
var devServer = new WebpackDevServer(compiler, {
  ...
  // override service worker path restriction
  headers: {
    'Service-Worker-Allowed': '/'
  }
});
```

**Comment by reflog** [comment]
Even better. Thanks guys. It's a pleasure using this while prototyping without a backend, thank you!

**Comment by DarrylD** [comment]
Do I have to `eject` in order to use this solution? Looking to not eject.

**Comment by idiotWu** [comment]
@DarrylD yep, otherwise you are not able to inject third-party dependencies.

**Comment by idiotWu** [comment]
@DarrylD @reflog hey guys, I just came up with an idea: can we use [file-loader](https://github.com/webpack-contrib/file-loader) to emit the `sw.js`?

We can code like:

```js
import scriptURL from 'file-loader?name=sw.js!path_to_your_mocker.js'
import { createClient } from 'service-mocker/client'

const client = createClient(scriptURL);
```

I'm traveling right now so I'm not able to test it :(. But I suppose it should work as expected.

**Comment by DarrylD** [comment]
I'm too traveling (how ironic!), I'll test it soon as I get a moment to experiment.

**Comment by idiotWu** [comment]
@DarrylD it seems that the emitted file won't be bundled with webpack 😢 :

<img width="435" alt="screenshot" src="https://cloud.githubusercontent.com/assets/6022672/24490421/181198ea-1555-11e7-849c-85c560dc001f.png">

Maybe we need to write another worker loader...

**Comment by idiotWu** [comment]
Got one possible solution which is inspired by [worker-loader](https://github.com/webpack-contrib/worker-loader):

```js
// sw-loader.js
const SingleEntryPlugin = require('webpack/lib/SingleEntryPlugin');

module.exports = function swLoader() {}

module.exports.pitch = function pitch(request) {
  if (!this.webpack) {
    throw new Error('Only usable with webpack.');
  }

  const callback = this.async();

  const swCompiler = this._compilation.createChildCompiler('sw', {
    filename: 'sw.js',
  });

  swCompiler.apply(new SingleEntryPlugin(this.context, `!!${request}`, 'main'));

  swCompiler.runAsChild((err, entries, compilation) => {
    if (err) return callback(err);
    if (entries[0]) {
      const swFile = entries[0].files[0];
      return callback(null, `module.exports = __webpack_public_path__ + ${JSON.stringify(swFile)};`);
    }
    return callback(null, null);
  });
}
```

I'll pack a loader as soon as I get back to work :)

**Comment by idiotWu** [comment]
@DarrylD done here: https://github.com/idiotWu/sw-loader

Usage with CRA:

```js
// eslint-disable-next-line import/no-webpack-loader-syntax
import scriptURL from 'path/to/node_modules/sw-loader!./sw.js';
```

**Comment by DarrylD** [comment]
Works perfect!
