### ISSUE TITLE
ngc+AOT+webpack - compile error

### ISSUE THREAD

**Issue by BogdanDumitruMarian** [service-mocker/service-mocker#26]
## Issue Summary

The following error occurs, when I try to build my project using webpack and taking advantage of AOT

_Error: Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 3:22 in the original .ts file), resolving symbol ExtandableRequest in D:/01_trunk/angular2-webpack-starter/node_modules/service-mocker/server/request.d.ts, resolving symbol MockerRequest in D:/01_trunk/angular2-webpack-starter/node_modules/service-mocker/server/request.d.ts_ 

I have a feeling that it is related to this: https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5#.1ubrczudd ... 

Tsc works just fine.

## Expected Behavior
Succesful compilation.

## Environment
- Version of service-mocker: 1.1.0

**Comment by idiotWu** [comment]
Sorry I am not familiar with angular 2. Will it be possible to do AoT compilation only in production?

**Comment by idiotWu** [comment]
@BogdanDumitruMarian we've just released 2.0.0 version, can you upgrade your service-mocker and test it again?

**Comment by BogdanDumitruMarian** [comment]
Hello, it seems to work now.
