### ISSUE TITLE
Problems with basinc routing

### ISSUE THREAD

**Issue by BogdanDumitruMarian** [service-mocker/service-mocker#35]
## Environment

- Browser: All
- Version of service-mocker: 2.0.0

## Current Behavior
Basic routing doesn't work.

## Steps to Reproduce

Webpack 2.2.0
sw-loader:
 * import scriptURL from 'sw-loader!./assets/server-mock/server.bundle.js';
 * const client = createClient(scriptURL);

server.bundle.js:
 ```
router.put('/groups/:id', (req, res) => {
   return res.json({});
 });
```

Trying a similar link gives 404: 'localhost/groups/1'
  * _Uncaught TypeError: Cannot read property '0' of undefined_
 
I've debugged a little bit, and the error occurs in service-mocker/server/request.js:
   ```
// skip full matched string at [0]
    var max = matches.length;
    for (var i = 1; i < max; i++) {
      var name = keys[i - 1].name;                  -----> keys is undefined.

      params[name] = decodeParam(matches[i]);
    }
```

**Comment by idiotWu** [comment]
Can you provide a link to the repo that reproduces this issue?

**Comment by matt-gadd** [comment]
@idiotWu I believe it's due to https://github.com/service-mocker/service-mocker/blob/develop/src/server/router.js#L149 - `regex.keys` is always undefined.

Changing the usage for `path-to-regexp` seemed to work for me: https://github.com/service-mocker/service-mocker/compare/develop...matt-gadd:regexp-keys

**Comment by idiotWu** [comment]
@matt-gadd thanks for looking into! The `.keys` property is added by [path-to-regexp](https://github.com/pillarjs/path-to-regexp/blob/master/index.d.ts#L7) module and it should always be an array. 

Actually in my tests I could not get `undefined` for `.keys` property :(

**Comment by matt-gadd** [comment]
@idiotWu yep sorry I didn't see that it did that 👍. In my case (not sure about the original poster), I had 2 versions of `path-to-regexp` (from another dep) in `node_modules`, with `npm` hoisting the old version which caused the issue.

**Comment by BogdanDumitruMarian** [comment]
Hi guys. Never really got the chance to look into it seriously, so I just worked around it. I'll give @matt-gadd's hint a go, when I get in front of the workstation.

**Comment by BogdanDumitruMarian** [comment]
Hello again. Looks like 'npm cache clean' did the trick. I think path-to-regexp was the problem, as I do have two versions of it in my project. Sorry for the delay.

**Comment by idiotWu** [comment]
If so, I think we are not likely to fix this issue since it's not supposed to happen while npm resolves correctly.
