### ISSUE TITLE
Auto reload with webpack

### ISSUE THREAD

**Issue by caesarsol** [service-mocker/service-mocker#36]
## Environment

- Browser: Chrome 59
- Version of service-mocker: 2.0.0

I'm not getting webpack to refresh the ServiceWorker code when I save the file.

Is it intended behavior or am I misconfiguring?

Using `sw-loader` with the code:

```js
const serverMockUrl = require('sw-loader!server-mock')
const { createClient } = require('service-mocker/client')
createClient(serverMockUrl).ready.then(() => console.log('ready'))
```

Thanks! 

Very cool idea for this package by the way 😉  Keep up the good work!

**Comment by idiotWu** [comment]
I just can't reproduce this issue with my own code :(. Can you provide a little demo that reproduces this?

**Comment by caesarsol** [comment]
I actually just wanted to know if it works for you: if you edit the "server" file and save, does your browser refresh with the new version of the service worker?

**Comment by idiotWu** [comment]
Well it took me really a long time to figure out where the problem is: sw-loader emits a static path string to the script resource, therefore the compilation returns a same result every time so it's being ignored by webpack cache policy 🤣 .

Try upgrading sw-loader to v0.1.1 to solve this issue.

**Comment by caesarsol** [comment]
@idiotWu I was debugging as well, almost got to the same conclusion! Trying it out now.

**Comment by caesarsol** [comment]
Works wonderfully!

Just a final question, is hot reload of the ServiceWorker supported?

I'm working on a way to have it immediately reloaded for every change in the server script, are you interested?

**Comment by idiotWu** [comment]
Currently it doesn't. But I think we can use `ServiceWorkerRegistration.update()` method to achieve this if needed.

**Comment by caesarsol** [comment]
I'm simply re-running `createClient()` and it works well. 

The only problem is to detect when a module is changed, because `module.hot.accept('server.js', ...)` doesn't work since the server module is not really imported in my code but in the service worker.

The only solutions I've found are:

1. Import the file just to have webpack watch it
2. Use [`require.context`](https://webpack.github.io/docs/hot-module-replacement.html#example-3-hot-module-replace-with-require-context), which imports the file anyway so there's no real gain

The working code in case 1 is:

```js
const serverMockUrl = require('sw-loader!../server-mock/index.js')
const { createClient } = require('service-mocker/client')

let swUpdate
createClient(serverMockUrl).ready.then(registration => {
  swUpdate = () => registration.update()
})

if (module.hot) {
  require('server-mock/index.js') // Only to have it watched by webpack
  module.hot.accept('server-mock/index.js', () => {
    require('server-mock/index.js') // Only to have it watched by webpack
    swUpdate()
  })
}
```

Which is actually enough for me, even if the code is imported two times :)

Do you think there is a better way?

**Comment by idiotWu** [comment]
Interesting. 

I'm not familiar with the mechanism underlying webpack hot reloading so I may not give any further advices. But AFAIK you will get some issues while running on legacy browsers, on which the `registration.update()` method actually does nothing (see [legacy/client.js](https://github.com/service-mocker/service-mocker/blob/develop/src/client/legacy/client.js#L83-L90)).

**Comment by caesarsol** [comment]
Yeah, that's out of my use case because I only develop on Chrome, and I use `service-mocker` only in development 😉 

Thanks for everything!
