### ISSUE TITLE
Wildcard URL param doesn't treat well empty param

### ISSUE THREAD

**Issue by caesarsol** [service-mocker/service-mocker#37]
## Environment

- Browser: Chrome 59
- Version of service-mocker: 2.0.0

## Expected Behavior
Wildcard URL parameters should give an `undefined` content when empty

## Current Behavior
They are instead `"undefined"` (a string containing the word "undefined")

## Steps to Reproduce
```js
// sw.js
import { createServer } from 'service-mocker/server'
const { router } = createServer()
router.get(`/asd/:path*`, (req, res) => {
  const { path } = req.params
  if (path === 'undefined') {
    console.warn(`Path is the string "undefined"!`)
  } else {
    console.log(`Path is "${path}"`)
  }
})

// index.js
window.fetch(`/asd/foo/bar`) // => Log: Path is "foo/bar"
window.fetch(`/asd/`) // => Warning: Path is the string "undefined"!
```

**Comment by idiotWu** [comment]
I don't think `"/asd/:path*"` is a valid express-style routing. You can't use wildcards in parameter names. Try either `"/asd/:path/*"` or `"/asd/:path"`.

**Comment by caesarsol** [comment]
It is!

> Express uses path-to-regexp for matching the route paths; see the path-to-regexp documentation for all the possibilities in defining route paths.

> Parameters can be suffixed with an asterisk (*) to denote a zero or more parameter matches. The prefix is taken into account for each match.
> `var re = pathToRegexp('/:foo*', keys)`

https://www.npmjs.com/package/path-to-regexp#zero-or-more

**Comment by idiotWu** [comment]
Oh, my mistake. Will fix it soon!

**Comment by idiotWu** [comment]
v2.0.1 is out 🎉
