### ISSUE TITLE
Add middlewares into the server

### ISSUE THREAD

**Issue by Spy-Seth** [service-mocker/service-mocker#39]
It could be nice to have a simple middleware mechanism into the `MockerServer` (like express). It could allow to add some generic logic around each route: simulate latency, add header to the response... 

What did you think about it?

**Comment by idiotWu** [comment]
> @VincentBel in #1:
>
> I think it is meaningless for developers to set up a full-featured mock server. Developers should write mock server code easily like [nock](https://github.com/node-nock/nock), but rather than a full-featured [express](https://github.com/expressjs/express) app.

Technically possible though 😆

**Comment by VincentBel** [comment]
@idiotWu yeah, initially I think mock server should be lightweight, and users can rarely use something like middleware. 😆 

Middleware is great, I think it do no harm to add middleware to mocker server. And some users can use middleware to handle some logic easily.

**Comment by idiotWu** [comment]
So what kind of middleware do we need?

#### 1. Full featured express middleware:

```ts
app.use([path], callback)
```

#### 2. Or simple reducers:

```ts
app.use(callback)
```

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BR4TCTD50DR69QB0A8PX3WDV/Full%20featured)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BR4TCTD50DR69QB0A8PX3WDV/Full%20featured/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BR4TCTD50DR69QB0A8PX3WDV/Reducers%20only)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BR4TCTD50DR69QB0A8PX3WDV/Reducers%20only/vote)

**Comment by Spy-Seth** [comment]
I think a simple reducers could be enough. Keep it simple :)

**Comment by idiotWu** [comment]
@Spy-Seth yep, and we can mount it via `new Server(baseURL)`.

**Comment by VincentBel** [comment]
@Spy-Seth [v2.1.0](https://github.com/service-mocker/service-mocker/releases/tag/v2.1.0) released.

**Comment by Spy-Seth** [comment]
🎉

**Comment by brettstack** [comment]
I'm getting error that the request object is read only. How do I set the path and method in middleware?

**Comment by dolphin-wood** [comment]
@brettstack the `MockerRequest` class is inherited from native `Request`, so you are not able to modify those props unless:

```js
// not recommended
Object.defineProperty(req, 'method', {
     value: 'blabla',
     writable: false,
     enumerable: true,
     configurable: true,
 });
```

IMO you can assign new props instead of overwriting existing props 😅.

**Comment by brettstack** [comment]
However, the router is based on `path` and `method`... This makes it impossible to change these in middleware. My specific use case: the application I'm working on sends all requests as `POST` and describe the HTTP request in the body (i.e. things like path, method, headers are defined in the body). I want to then transform these in the middleware to "proper" HTTP requests... Any ideas?

**Comment by dolphin-wood** [comment]
That makes me think of preflight requests...

However even if you modified `req.method`, the request would not be streamed into proper routings because the routing selection has already finished: https://github.com/service-mocker/service-mocker/blob/3650157256b9666cafdddfa10cc328ba66a3880c/src/server/router.js#L218-L233

**Comment by brettstack** [comment]
I see. Any reason the middleware execution can't be moved above that block?

**Comment by brettstack** [comment]
Also, I found that out myself the hard way after applying `Object.defineProperty` as you described above. I can see the `req` object has been mutated but it doesn't match the route. :)

**Comment by dolphin-wood** [comment]
> Any reason the middleware execution can't be moved above that block?

Then all the requests will be "mocked" because `fetchEvent.respondWith()` is called, which means unhandled routings will _NEVER_ be sent to your real backend server.

**Comment by brettstack** [comment]
We can't reject the promise if it doesn't find a match after applying middleware? I know the caller of this function isn't currently set up to take a promise. Looks like it just expects true or false returned. I'm obviously not familiar enough with the base to understand the impact

**Comment by brettstack** [comment]
Actually looks like the return value of match isn't even used https://github.com/service-mocker/service-mocker/blob/14f1a7ad282b69e5c4c069c5bb5964b0693e6bc3/src/server/server.js#L73

**Comment by brettstack** [comment]
Not at a computer, but you should be able to do:

1. Middleware promises
2. Loop through routes
3. On route match: callback and return

MockerRequest would no longer be able to receive the matched rule but could instead take in all rules

**Comment by dolphin-wood** [comment]
It's not about route match but about fetch event itself. `fetchEvent.respondWith()` method must be called synchronously:

```js
// ✅ Good
self.addEventListener('fetch', (evt) => {
  evt.respondWith(res);
});

// ❌ Bad
self.addEventListener('fetch', (evt) => {
  Promise.resolve().then(
    evt.respondWith(res)
  );
});
```

Meanwhile, we need to support asynchronous middleware and routing handlers. So the problem is: **we can not call `fetchEvent.respondWith()` after asynchronous stuffs**.

The current strategy is:

1. construct a deferred promise which could be resolved later
2. call `fetchEvent.respondWith(deferredPromise)` if route matches
3. apply (asynchronous) middleware and routing handles
4. resolve the deferred promise with response `deferredPromise.resolve(res)`

The implement details could be found in https://github.com/service-mocker/service-mocker/blob/3650157256b9666cafdddfa10cc328ba66a3880c/src/server/response.js#L64-L73 and https://github.com/service-mocker/service-mocker/blob/3650157256b9666cafdddfa10cc328ba66a3880c/src/server/response.js#L184-L225

**Comment by brettstack** [comment]
Workaround:

```js
const unwrapperMiddleware = ({ basePath = '/', method = 'post' } = {}) => {
  router[method](basePath, (req, res) => {
    const route = router._rules.find(rule => rule.regex.test(req.path) && (req.method === rule.method || rule.isAll))

    if (route) {
      route.callback.call(req._event, req, res)
    }
  })

  return (req, res) => {
    return req.clone().json().then(body => {
      Object.keys(body.headers).forEach(headerKey => {
        req.headers.set(headerKey, body.headers[headerKey])
      })
      Object.defineProperty(req, 'path', {
        value: body.path,
        writable: false,
        enumerable: true,
        configurable: true
      })
      Object.defineProperty(req, 'method', {
        value: body.method,
        writable: false,
        enumerable: true,
        configurable: true
      })
    })
  }
}

router.use(unwrapperMiddleware())
```
