### ISSUE TITLE
createClient(scriptURL).ready does not resolve at root /

### ISSUE THREAD

**Issue by brettstack** [service-mocker/service-mocker#41]
## Environment

- Browser: Chrome
- Version of service-mocker: 2.0.1

When I load my app at `localhost:3000/users` it works fine. However, when I load it at the root `localhost:3000`, `createClient(scriptURL).ready` never resolves (or rejects). I'm using Webpack + sw-loader. I can see in the network tab it loads the service worker, and no error in console.

```js
import { createClient } from 'service-mocker/client'
import scriptURL from 'sw-loader?name=mock-api-sw.js!./mock-api-server.js'

const client = createClient(scriptURL).ready
  .then(r => console.log('success', r))
  .catch(e => console.error('error', e))
export default client
```

```js
import { createServer } from 'service-mocker/server'

const { router } = createServer()

router.get('/users', (req, res) => {
  res.json([{
    name: 'Brett'
  }])
})

```

**Comment by idiotWu** [comment]
Can you post a screenshot of `Chrome DevTools > Application > Service Workers`? I think this issue is related to service worker registration scope.

Screenshot example:
<img width="574" alt="2017-08-24 05 00 21" src="https://user-images.githubusercontent.com/6022672/29635853-590dadbe-8889-11e7-9fab-5a205a1637d6.png">

**Comment by brettstack** [comment]
<img width="1258" alt="screen shot 2017-08-24 at 11 57 11 am" src="https://user-images.githubusercontent.com/1882775/29683525-80695a68-88c3-11e7-8c8f-b0322ee58064.png">

**Comment by brettstack** [comment]
As you can see, it's running, it's just the `createClient(scriptURL).ready` Promise never resolves (or rejects). Navigating to /users (or any non-root path) works.

**Comment by idiotWu** [comment]
That is confusing 🤔

Is there any demo reproduces this issue?

**Comment by brettstack** [comment]
No easy demo I can give and I can't think of anything funky I'm doing that would break it for root... I was hoping you just might know why the promise isn't resolving haha. If you can't think of anything I'll dive into it myself when it becomes annoying enough (I'm only including service-mocker during dev so does not affect prod)

**Comment by idiotWu** [comment]
Not sure if this issue is related to registration scope. You can try unregistering service worker (by click the "Unregister" link) and initializing mocker from root (ie navigate to http://localhost:3000).

**Comment by brettstack** [comment]
Yea I've tried unregistering. I stepped through some of the transpiled code
and see it's not resolving where it does for non-root paths... But
debugging transpiled code is not a fun task. I'll pick it back up again
when it bugs me enough and will follow up with CR if necessary. If you come
across the problem/solution, ping the thread and let me know. :)

**Comment by brettstack** [comment]
I'm no longer getting this issue on 2.1.2
